"""Add project_id column

Revision ID: 0ee0bdbc0311
Revises: 53c4c8176ad3
Create Date: 2025-12-08 23:06:40.125481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee0bdbc0311'
down_revision: Union[str, Sequence[str], None] = '53c4c8176ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('project_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'analysis_runs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.drop_column('analysis_runs', 'project_id')
    # ### end Alembic commands ###
