"""Initial schema with projects and graph

Revision ID: 53c4c8176ad3
Revises: 
Create Date: 2025-12-08 16:35:27.933669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '53c4c8176ad3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('code_summaries',
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('file_path')
    )
    op.create_table('file_dependencies',
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('target_file', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('source_file', 'target_file')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.run_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index(op.f('ix_business_rules_file_path'), 'business_rules', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_rules_file_path'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_table('projects')
    op.drop_table('file_dependencies')
    op.drop_table('code_summaries')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
